name: Lab CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

env:
  BUILD_TYPE: Release

jobs:
  build-project:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake
    
    - name: Cache build directories
      uses: actions/cache@v3
      with:
        path: |
          formatter_lib/build
          formatter_ex_lib/build
          hello_world_application/build
          solver_lib/build
          solver_application/build
        key: ${{ runner.os }}-build-${{ github.sha }}
    
    - name: Build formatter_lib
      working-directory: formatter_lib
      run: |
        mkdir -p build && cd build
        cmake -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }} ..
        cmake --build .
    
    - name: Build formatter_ex_lib
      working-directory: formatter_ex_lib
      run: |
        mkdir -p build && cd build
        cmake -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }} ..
        cmake --build .
    
    - name: Build hello_world_application
      working-directory: hello_world_application
      run: |
        mkdir -p build && cd build
        cmake -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }} ..
        cmake --build .
    
    - name: Build solver_lib
      working-directory: solver_lib
      run: |
        mkdir -p build && cd build
        cmake -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }} ..
        cmake --build .
    
    - name: Build solver_application
      working-directory: solver_application
      run: |
        mkdir -p build && cd build
        cmake -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }} ..
        cmake --build .
